apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: yuvraj
  MYSQL_DATABASE: lms_db
  MYSQL_USER: root
  MYSQL_PASSWORD: yuvraj
  MYSQL_DB_URL: mysql+pymysql://root:yuvraj@mysql-service:3306/lms_db
  SECRET_KEY: 987987654654321113_super_secret_session_key_32bytes
  JWT_SECRET_KEY: 4654864653546816_jwt_secret_key_at_least_32_bytes_long